language: node_js
node_js:
- 4.5.0
- 6.2.2
cache:
  directories:
    - node_modules
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
- sudo pip install -r requirements.txt
- npm install -g webpack
- npm install -g webpack-dev-server
- npm install
script:
- npm run tslint
- npm run test:acceptance
notifications:
  email:
  - stollenwerk@kitconcept.com
